preset: psr2

enabled:
  - align_double_arrow
  - align_equals
  - alpha_ordered_imports
  - blank_line_before_return
  - concat_with_spaces
  - hash_to_slash_comment
  - method_separation
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_extra_block_blank_lines
  - no_empty_comment
  - no_extra_consecutive_blank_lines
  - no_php4_constructor
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_unused_imports
