preset: psr2

enabled:
  - align_double_arrow
  - align_equals
  - alpha_ordered_imports
  - blank_line_before_return
  - concat_with_spaces
  - hash_to_slash_comment
  - method_separation
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
